# Generated by Django 4.1.1 on 2022-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizApp", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
