# Generated by Django 4.1.1 on 2022-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizApp", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
